# Copyright (c) 1999-2009, 2013-2017, 2020 Paul Mattes.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the names of Paul Mattes nor the names of his contributors
#       may be used to endorse or promote products derived from this software
#       without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY PAUL MATTES "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL PAUL MATTES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

# Makefile for c3270 (console-based 3270 emulator)

RM = rm -f
CC = gcc

all: c3270 x3270if

HOST = x86_64-unknown-linux-gnu
include c3270_files.mk libs.mk

VOBJS = $(C3270_OBJECTS) fallbacks.o

OBJS1 = $(VOBJS) version.o

LIBDIR = ${exec_prefix}/lib
prefix = /usr/local
exec_prefix = ${prefix}
sysconfdir = ${prefix}/etc
datarootdir = ${prefix}/share
LIBX3270DIR = ${sysconfdir}/x3270
MANDIR = ${datarootdir}/man
BINDIR = ${exec_prefix}/bin
INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL}
INSTALL_DATA = ${INSTALL} -m 644

CCOPTIONS =  -Wall -Wsign-compare -std=c99 -pedantic -Wno-variadic-macros -MMD -MP
XCPPFLAGS = -I. -I$(THIS) -I$(TOP)/Common/c3270 -I$(TOP)/Common -I$(TOP)/include -DLIBX3270DIR=\"$(LIBX3270DIR)\" -D_POSIX_SOURCE -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_XOPEN_SOURCE
CFLAGS = $(CCOPTIONS) $(CDEBUGFLAGS) $(XCPPFLAGS) -g -O2
LDFLAGS = 
LIBS = -lncursesw -lutil 

XVERSION = xversion.c
version.o: mkversion.sh $(VOBJS) version.txt
	$(RM) $(XVERSION)
	sh $< c3270 $(filter %.txt,$^) >$(XVERSION)
	$(CC) $(CFLAGS) -c -o $@ $(XVERSION)
	$(RM) $(XVERSION)

FALLBACKS = fb-common fb-printSession fb-messages fb-composeMap fb-c3270
fallbacks.c: mkfb $(FALLBACKS)
	$(RM) $@
	./mkfb -c -o $@ $(filter-out mkfb,$^)

mkfb: mkfb.c
	$(CC) $(CFLAGS) -o $@ $(filter %.c,$^)

keypad.o: compiled_keypad.h

compiled_keypad.h: keypad.full keypad.labels keypad.map keypad.outline keypad.callbacks mkkeypad
	./mkkeypad -I$(TOP)/Common/c3270 >$@

c3270: $(OBJS1) $(DEP3270) $(DEP3270I) $(DEP32XX) $(DEP3270STUBS) $(DEP32XX)
	$(CC) -o $@ $(OBJS1) $(LDFLAGS) $(LD3270) $(LD3270I) $(LD32XX) $(LD3270STUBS) $(LIBS)

x3270if: ../x3270if/x3270if
	cp -p ../x3270if/x3270if $@

man:: c3270.man
	if [ ! -f $(notdir $^) ]; then cp $< $(notdir $^); fi
man:: x3270-script.man
	if [ ! -f $(notdir $^) ]; then cp $< $(notdir $^); fi
man:: ibm_hosts.man
	if [ ! -f $(notdir $^) ]; then cp $< $(notdir $^); fi

install:: c3270
	[ -d $(DESTDIR)$(BINDIR) ] || \
		mkdir -p $(DESTDIR)$(BINDIR)
	$(INSTALL_PROGRAM) c3270 $(DESTDIR)$(BINDIR)/c3270
install:: ibm_hosts
	[ -d $(DESTDIR)$(LIBX3270DIR) ] || \
		mkdir -p $(DESTDIR)$(LIBX3270DIR)
	[ -r $(DESTDIR)$(LIBX3270DIR)/ibm_hosts ] || \
		$(INSTALL_DATA) $< $(DESTDIR)$(LIBX3270DIR)/ibm_hosts

install.man: man
	[ -d $(DESTDIR)$(MANDIR)/man1 ] || \
		mkdir -p $(DESTDIR)$(MANDIR)/man1
	[ -d $(DESTDIR)$(MANDIR)/man5 ] || \
		mkdir -p $(DESTDIR)$(MANDIR)/man5
	$(INSTALL_DATA) c3270.man $(DESTDIR)$(MANDIR)/man1/c3270.1
	$(INSTALL_DATA) x3270-script.man $(DESTDIR)$(MANDIR)/man1/x3270-script.1
	$(INSTALL_DATA) ibm_hosts.man $(DESTDIR)$(MANDIR)/man5/ibm_hosts.5

clean:
	$(RM) *.o mkfb fallbacks.c compiled_keypad.h

clobber: clean
	$(RM) c3270 *.d *.man

# Include auto-generated dependencies.
-include $(OBJS:.o=.d) mkfb.d
